// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AMap: typeof import('./../src/components/AMap.vue')['default']
    Navbar: typeof import('./../src/components/Navbar.vue')['default']
    Selector: typeof import('./../src/components/Selector.vue')['default']
    SwitchType: typeof import('./../src/components/SwitchType.vue')['default']
  }
}
